import type { NextApiRequest, NextApiResponse } from "next";
import { Employee } from "../../lib/types";

const dummyEmployees: Employee[] = [
  {
    id: 0,
    firstName: "Juan",
    lastName: "",
    middleName: "",
    suffix: "",
    address1: "Brgy. Sto. Nino",
    address2: "Calumpit, Bulacan",
    salaryType: "daily",
    salaryAmount: 500,
    restDays: { 0: true, 1: false, 2: false, 3: false, 4: false, 5: false, 6: false },
    workingHours: { from: "08:00", to: "17:00" },
    eligibilities: { SSS: true, PHIC: true, HDMF: true },
  },
  {
    id: 1,
    firstName: "Pedro",
    lastName: "",
    middleName: "",
    suffix: "Sr.",
    address1: "Brgy. Sto. Nino",
    address2: "Calumpit, Bulacan",
    salaryType: "daily",
    salaryAmount: 650,
    restDays: { 0: true, 1: false, 2: false, 3: false, 4: false, 5: false, 6: true },
    workingHours: { from: "07:00", to: "16:00" },
    eligibilities: { SSS: true, PHIC: true, HDMF: true },
  },
  {
    id: 2,
    firstName: "Diego",
    lastName: "",
    middleName: "",
    suffix: "",
    address1: "Brgy. Sto. Nino",
    address2: "Calumpit, Bulacan",
    salaryType: "fixed",
    salaryAmount: 19650,
    restDays: { 0: true, 1: false, 2: false, 3: false, 4: false, 5: false, 6: true },
    workingHours: { from: "06:00", to: "15:00" },
    eligibilities: { SSS: true, PHIC: true, HDMF: false },
  },
  {
    id: 3,
    firstName: "Pablo",
    lastName: "",
    middleName: "",
    suffix: "",
    address1: "Brgy. Sto. Nino",
    address2: "Calumpit, Bulacan",
    salaryType: "fixed",
    salaryAmount: 25331,
    restDays: { 0: true, 1: false, 2: false, 3: false, 4: false, 5: false, 6: true },
    workingHours: { from: "06:00", to: "15:00" },
    eligibilities: { SSS: true, PHIC: true, HDMF: false },
  },
  {
    id: 4,
    firstName: "Jose",
    lastName: "",
    middleName: "",
    suffix: "",
    address1: "Brgy. Sto. Nino",
    address2: "Calumpit, Bulacan",
    salaryType: "fixed",
    salaryAmount: 31442,
    restDays: { 0: true, 1: false, 2: false, 3: false, 4: false, 5: false, 6: true },
    workingHours: { from: "06:00", to: "15:00" },
    eligibilities: { SSS: true, PHIC: true, HDMF: false },
  },
  {
    id: 5,
    firstName: "Ferdinand",
    lastName: "",
    middleName: "",
    suffix: "",
    address1: "Brgy. Sto. Nino",
    address2: "Calumpit, Bulacan",
    salaryType: "daily",
    salaryAmount: 1694,
    restDays: { 0: true, 1: false, 2: false, 3: false, 4: false, 5: false, 6: true },
    workingHours: { from: "06:00", to: "15:00" },
    eligibilities: { SSS: true, PHIC: true, HDMF: false },
  },
  {
    id: 6,
    firstName: "Richard",
    lastName: "",
    middleName: "",
    suffix: "",
    address1: "Brgy. Sto. Nino",
    address2: "Calumpit, Bulacan",
    salaryType: "daily",
    salaryAmount: 2141,
    restDays: { 0: true, 1: false, 2: false, 3: false, 4: false, 5: false, 6: true },
    workingHours: { from: "06:00", to: "15:00" },
    eligibilities: { SSS: true, PHIC: true, HDMF: false },
  },
  {
    id: 7,
    firstName: "Victor",
    lastName: "",
    middleName: "",
    suffix: "",
    address1: "Brgy. Sto. Nino",
    address2: "Calumpit, Bulacan",
    salaryType: "daily",
    salaryAmount: 2141,
    restDays: { 0: true, 1: false, 2: false, 3: false, 4: false, 5: false, 6: true },
    workingHours: { from: "06:00", to: "15:00" },
    eligibilities: { SSS: true, PHIC: true, HDMF: false },
  },
];

export default function handler(req: NextApiRequest, res: NextApiResponse<Employee[]>) {
  res.status(200).json(dummyEmployees);
}
